#!/usr/bin/env bash
set -euo pipefail

HOSTS=(
  mallard
  pintail
)

for host in "${HOSTS[@]}"; do
  echo
  echo "=== Deploying $host ==="
  sudo nix run nixpkgs#nixos-rebuild -- \
    switch \
    --flake .#$host \
    --target-host $host \
    --elevate=sudo
done

echo
echo "All flew successfully."
echo
