#!/usr/bin/env bash

set -euo pipefail

HOSTS=("duck1" "duck2")

for host in "${HOSTS[@]}"; do
  echo "===== deploying $host ====="

  nixos-rebuild switch \
    --flake .#"${host}" \
    --target-host "${host}" \
    --use-remote-sudo

done
